# Generated by Django 3.2.5 on 2022-08-12 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='r_i',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.ingredient')),
                ('r_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.recipe')),
            ],
        ),
    ]
