# Generated by Django 3.2.5 on 2022-08-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='playground.Ingredient'),
        ),
        migrations.DeleteModel(
            name='r_i',
        ),
    ]
