# Generated by Django 3.2.5 on 2022-08-12 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_auto_20220812_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
