# Generated by Django 3.2.5 on 2022-08-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_ingredient_recipe'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['ingredient_name'], name='playground__ingredi_4028f9_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['recipe_name', 'ingredient_count'], name='playground__recipe__1124cd_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['ingredient_count'], name='playground__ingredi_1459e9_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['recipe_name'], name='playground__recipe__8f9d21_idx'),
        ),
    ]
