# Generated by Django 3.2.5 on 2022-08-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0009_auto_20220814_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='source',
            field=models.CharField(max_length=100),
        ),
    ]
