# Generated by Django 3.2.5 on 2022-08-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0010_auto_20220814_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
